import time
class Dialogue:
    def __init__(self):
        pass
    def opening_scene(self):
        print("[You awake sitting on an Imperial wagon driving you and three other prisoners down a snowy mountain pass.]")
        time.sleep(2)
        print("[You are all seated and bound; the man dressed in fine apparel has a cloth wrapped around his mouth.]")
        time.sleep(2)
        print("Ralof: Hey, you. You're finally awake.")
        time.sleep(2)
        print("Ralof: You were trying to cross the border, right?")
        time.sleep(2)
        print("Ralof: Walked right into that Imperial ambush, same as us, and that thief over there.")
        time.sleep(2)
        print("Lokir: Darn you Stormcloaks. Skyrim was fine until you came along.")
        time.sleep(2)
        print("Lokir: If they hadn't been looking for you, I could've stolen that horse and been half way to Hammerfell.")
        time.sleep(2)
        print("Lokir: You there.")
        time.sleep(2)
        print("Lokir: You and me - we shouldn't be here. It's these Stormcloaks the Empire wants.")
        time.sleep(2)
        print("Ralof: We're all brothers and sisters in binds now, thief.")
        time.sleep(2)
        print("You hear a Imperial Solder yell from the front of the wagon: Shut up back there!")
        time.sleep(2)
        print("[Lokir looks at the gagged man.]")
        time.sleep(2)
        print("Lokir: And what's wrong with him?")
        time.sleep(2)
        print("Ralof: Watch your tongue! You're speaking to Ulfric Stormcloak, the true High King.")
        time.sleep(2)
        print("Lokir: Ulfric? The Jarl of Windhelm? You're the leader of the rebellion.")
        time.sleep(2)
        print("Lokir: But if they captured you... Oh gods, where are they taking us?")
        time.sleep(2)
        print("Ralof: I don't know where we're going, but Sovngarde awaits.")
        time.sleep(2)
        print("Lokir: No, this can't be happening. This isn't happening.")
        time.sleep(2)
        print("Ralof: Hey, what village are you from, horse thief?")
        time.sleep(2)
        print("Lokir: Why do you care?")
        time.sleep(2)
        print("Ralof: A Nord's last thoughts should be of home.")
        time.sleep(2)
        print("Lokir: Rorikstead. I'm... I'm from Rorikstead.")
        time.sleep(2)
        print("[You approach the village of Helgen. A soldier calls out to the lead wagon.]")
        time.sleep(2)
        print("Imperial Soldier: General Tullius, sir! The headsman is waiting!")
        time.sleep(2)
        print("General Tullius: Good. Let's get this over with.")
        time.sleep(2)
        print("Lokir: Shor, Mara, Dibella, Kynareth, Akatosh. Divines, please help me!")
        time.sleep(2)
        print("Ralof: Look at him, General Tullius the Military Governor. And it looks like the Thalmor are with him.")
        time.sleep(2)
        print("Ralof: Darn elves. I bet they had something to do with this.")
        time.sleep(2)
        print("Ralof: This is Helgen. I used to be sweet on a girl from here.")
        time.sleep(2)
        print("Ralof: Wonder if Vilod is still making that mead with juniper berries mixed in.")
        time.sleep(2)
        print("Ralof: Funny... when I was a boy, Imperial walls and towers used to make me feel so safe.")
        time.sleep(2)
        print("[A man and son watch the prisoners pull into town.]")
        time.sleep(2)
        print("Haming: Who are they, daddy? Where are they going?")
        time.sleep(2)
        print("Torolf: You need to go inside, little cub.")
        time.sleep(2)
        print("Haming: Why? I want to watch the soldiers.")
        time.sleep(2)
        print("Torolf: Inside the house. Now.")
        time.sleep(2)
        print("[The wagon stops near the chopping block.]")
        time.sleep(2)
        print("Imperial Soldier: Whoa.")
        time.sleep(2)
        print("Lokir: Why are they stopping?")
        time.sleep(2)
        print("Ralof: Why do you think?")
        time.sleep(2)
        print("Ralof: End of the line.")
        time.sleep(2)
        print("Ralof: Let's go. Shouldn't keep the gods waiting for us.")
        time.sleep(2)
        print("[You and the other men stand up and start to walk off the wagon, you are last]")
        time.sleep(2)
        print("Lokir: No! Wait! We're not rebels!")
        time.sleep(2)
        print("Ralof: Face your death with some courage, thief.")
        time.sleep(2)
        print("Lokir: You've got to tell them! We weren't with you! This is a mistake!")
        time.sleep(2)
        print("Imperial Captain: Step towards the block when we call your name. One at a time.")
        time.sleep(2)
        print("Ralof: Empire loves their darn lists.")
        time.sleep(2)
        print("Hadvar: Ulfric Stormcloak. Jarl of Windhelm.")
        time.sleep(2)
        print("[Ulfric walks towards the chopping block, which is to the left]")
        time.sleep(2)
        print("Ralof: It has been an honor, Jarl Ulfric.")
        time.sleep(2)
        print("Hadvar: Ralof of Riverwood.")
        time.sleep(2)
        print("[Ralof walks towards the chopping block]")
        time.sleep(2)
        print("Hadvar: Lokir of Rorikstead.")
        time.sleep(2)
        print("Lokir: No, I'm not a rebel. You can't do this!")
        time.sleep(2)
        print("[Lokir begins to run forward]")
        time.sleep(2)
        print("Captain: Halt!")
        time.sleep(2)
        print("Lokir: You're not going to kill me!")
        time.sleep(2)
        print("[Lokir runs past the guards]")
        time.sleep(2)
        print("Captain: Archers!")
        time.sleep(2)
        print("[At the Captains command the archers let loose their arrows and Lokir is shot to the ground]")
        time.sleep(2)
        print("Captain: Anyone else feel like running?")
        time.sleep(2)
        print("Hadvar: Wait. You there. Step forward. Who are you?")
        time.sleep(2)
        print("[You walk forward and are now able to create you character]")